---
- name: configuring romcat9
  hosts: all 
  tasks: 
     - name: install tomcat9
       apt:
         name: tomcat9
         state: present
     - name: install tomcat9-admin
       apt: 
         name: tomcat9-admin
         state: present
     - name: copy tomcat-users.xml file
       copy: 
          src: tomcat-users.xml
          dest: /etc/tomcat9
     - name: change port
       replace: 
          regexp: 8080
          replace: 9090
          path: /etc/tomcat9/server.xml
     - name: restart tomct9
       service: 
          name: tomcat9
          state: restarted
     - name: wait
       pause:
         minutes: 1
     - name: check server1
       uri:
         url: http://172.31.30.30:9090
         status_code: 200
     - name: check server2
       uri:
         url: http://172.31.26.224:9090
         status_c0de: 200
...           
